# Generated by Django 2.2.17 on 2020-12-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_customtext_bvbvnbvnbv"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="jhghjggjhg",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
