# Generated by Django 2.2.17 on 2020-12-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_jhghjggjhg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='jhghjggjhg',
        ),
    ]
